themes: modern
menubar: false
plugins:
  - image
  - link
  - charmap
  - advlist
  - fullscreen
  - save
toolbar:
  - save | undo redo | fullscreen | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat | image | link | charmap | help
content_css: 
  - assets/tinymce.css