themes: modern
menubar: true
plugins:
  - image
  - link
  - charmap
  - advlist
  - fullscreen
toolbar:
  - fullscreen | undo redo | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat | image | link | charmap | help
content_css: 
  - assets/tinymce.css